# Font configuration (changes require restart)
font:
    size: 12
    # Normal (roman) font face
    normal:
        family: FantasqueSansMono Nerd Font
        # The `style` can be specified to pick a specific face.
        style: Regular

    # Bold font face
    bold:
        family: FantasqueSansMono Nerd Font
        # The `style` can be specified to pick a specific face.
        style: Bold

    # Italic font face
    italic:
        family: FantasqueSansMono Nerd Font
        # The `style` can be specified to pick a specific face.
        style: Italic

window:
    dimensions:
        columns: 100
        lines: 24

    padding:
        x: 0
        y: 0

background_opacity: 0.98
colors:
  # Default colors
  primary:
    background: '0x2a2426'
    foreground: '0xe6d6ac'

  # Normal colors
  normal:
    black:   '0x2a2426'
    red:     '0xe68183'
    green:   '0xa7c080'
    yellow:  '0xd9bb80'
    blue:    '0x7d7d7d'
    magenta: '0x659ba8'
    cyan:    '0x87c095'
    white:   '0xa7c080'

  # Bright colors
  bright:
    black:   '0x2a2426'
    red:     '0xe68183'
    green:   '0xa7c080'
    yellow:  '0xd9bb80'
    blue:    '0x7d7d7d'
    magenta: '0x659ba8'
    cyan:    '0x87c095'
    white:   '0xa7c080'

